# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_time_app', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.CharField(default='noemail', max_length=150),
        ),
    ]
