# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_time_app', '0003_userdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='fName',
            field=models.CharField(default='noFirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lName',
            field=models.CharField(default='noLastName', max_length=100),
        ),
    ]
